# cellranger software
cellranger: /home/keke/data2/app/cellranger-7.2.0/bin/cellranger
ref: /home/keke/data2/ref/refdata-gex-GRCh38-2020-A
memory: 64
threads: 12

# input data
input_file: /home/keke/data/tutorial/pipeline/sc-cellranger/sample.csv

# the results directory
output_directory: /home/keke/base/raw/tmp
